server:
  port: 9810

spring:
  #Postgresql
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 123456

jwt:
  secret: kdgKDBSAHFSDkjfhsFBSDBFDSFsalfjsaDAHDhfkjsdsfsdfsdfdsfGENSHIN
  #  60*60*24
  expiration: 86400



