server:
  port: 8091

spring:
  #Postgresql
  datasource:
    driver-class-name: org.postgresql.Driver
    #url: jdbc:postgresql://game-meet-werewolf.ngrok-free.app/Rental_ads_board
#    url: jdbc:postgresql://192.168.1.109:5432/Rental_ads_board
#    url: jdbc:postgresql://localhost:5432/postgres
    url: jdbc:postgresql://localhost:5432/Rental_ads_board
    username: postgres
#    password: admin
    password: hdu

avatar_storage:
  path: static\avatar

picture_storage:
  path: static\itemPicture

jwt:
  secret: fhajshVRBUslhfihvmfahFSFSGgliaebhgiojfcoSFSDFhgiwf
  #  60*60*24
  expiration: 86400

excludePaths: /board/login,/board/register


