server:
  port: 8091

spring:
  #Postgresql
  datasource:
    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://192.168.1.109:5432/Rental_ads_board
#    url: jdbc:postgresql://localhost:5432/postgres
    url: jdbc:postgresql://localhost:5432/Rental_ads_board
    username: postgres
#    password: admin
    password: hdu

jwt:
  secret: yssxfsfsfawnAgjluvvbgsfgdvebrhsrujrbcatyveynwyexmydmt
  #  60*60*24
  expiration: 86400

avatar_storage:
  path: static\avatar

picture_storage:
  path: static\itemPicture

excludePaths: /board/login,/board/register


